version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "migrations/**",
  "**/examples/**"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "dotnet-format"